---

- name: Update apt cache
  apt: update_cache=yes
  sudo: yes  

- name: Disable serial terminal 
  lineinfile: "dest=/boot/cmdline.txt state=present regexp='dwc_otg.lpm_enable=0 console=ttyAMA0,115200' line='dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait'"
  sudo: true

- name: Disable serial terminal (getty)
  lineinfile: "dest=/etc/inittab state=present regexp='T0:23:respawn:/sbin/getty -L ttyAMA0' line='# T0:23:respawn:/sbin/getty -L ttyAMA0 115200 vt100'"
  sudo: true

- shell: '/sbin/parted -s /dev/mmcblk0 mkpart primary 3277MB 16.0GB creates=/dev/mmcblk0p3'
  register: updated_partitions
  sudo: true

- name: Restart the server after partition update  
  command: "shutdown -r now"
  when: updated_partitions.changed
  sudo: true

- name: Wait for server to come up after partition update  
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay=30
  when: updated_partitions.changed
  sudo: false

- name: Create ext2 filesystem with 1024 bytes blocksize instead of the default 4096 bytes.  
  filesystem: fstype=ext2 dev=/dev/mmcblk0p3 opts="-b 1024"
  sudo: true

- name: Create /home/pi/data
  file: dest=/home/pi/data state=directory

- lineinfile: dest='/etc/default/rcS' line='RAMTMP=yes'
  sudo: true

- copy: src=files/fstab dest=/etc/fstab
  register: updated_mounts
  sudo: true

- file: src=/proc/self/mounts dest=/etc/mtab state=link
  sudo: true

- copy: src=files/rpi-rw dest=/usr/bin/rpi-rw mode=0755
  sudo: true

- copy: src=files/rpi-ro dest=/usr/bin/rpi-ro mode=0755
  sudo: true

- name: Restart the server after mount update  
  command: "shutdown -r now"
  when: updated_mounts.changed
  sudo: true

- name: Wait for server to come up after mount update  
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay=30
  when: updated_mounts.changed
  sudo: false

- name: Change /home/pi/data permissions
  file: dest=/home/pi/data owner=pi group=pi mode=777 state=directory
  sudo: true

